<?php
//--- This code is generated by ProBot ---
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Purchase;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class PurchaseController extends Controller{

	public function index(){
		$purchases=Purchase::paginate(10);
		return view("pages.erp.purchase.index_purchase",["purchases"=>$purchases]);
	}
	public function create(){
		$supplier=Supplier::all();
		// print_r($suppliers);

		return view("pages.erp.purchase.create_purchase",["suppliers"=>$supplier]);
	}
	public function store(Request $request){
//		Purchase::create($request->all());
		$purchase=new Purchase;
		$purchase->supplier_id=$request->cmbSupplier;
		$purchase->purshase_date=$request->txtPurshase_date;
		$purchase->discount=$request->txtDiscount;
		$purchase->order_total=$request->txtOrder_total;
		$purchase->paid_amount=$request->txtPaid_amount;
		$purchase->status=$request->txtStatus;
		$purchase->delivery_date=$request->txtDelivery_date;

		$purchase->save();
		return back()->with('success','Created Successfully.');

	}
	public function show($id){
		$purchase=Purchase::find($id);
		return view("pages.erp.purchase.show_purchase",["purchase"=>$purchase]);
	}
	public function edit(Purchase $purchase){
		$suppliers=Supplier::all();

		return view("pages.erp.purchase.edit_purchase",["purchase"=>$purchase,"suppliers"=>$suppliers]);
	}
	public function update(Request $request,Purchase $purchase){
//		$purchase->update($request->all());
		$purchase->supplier_id=$request->cmbSupplier;
		$purchase->purshase_date=$request->txtPurshase_date;
		$purchase->discount=$request->txtDiscount;
		$purchase->order_total=$request->txtOrder_total;
		$purchase->paid_amount=$request->txtPaid_amount;
		$purchase->status=$request->txtStatus;
		$purchase->delivery_date=$request->txtDelivery_date;

		$purchase->update();
		return redirect()->route("purchases.index")->with('success','Updated Successfully.');
  
	}
	public function destroy(Purchase $purchase){
		$purchase->delete();
		return redirect()->route("purchases.index")->with('success','Deleted Successfully.');
	}

	
}
